name: latest_ver

on:
  schedule:
    - cron: "30 0 * * *" # Triggers the workflow every day at 0:30 UTC
  workflow_dispatch: # Allow manual trigger workflows

jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    steps:
    - uses: kyanagimoto/get-latest-version@main
      with:
        repo-name: 'getsentry/sentry'
